repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use latest stable version
    hooks:
      - id: black
        files: .

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Use a specific compatible version
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests", "python-decouple",'fastapi', 'pydantic']
        args: [app]
        pass_filenames: false


  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

default_stages: [pre-commit, pre-push]